/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author krm5188
 */
public class AccountInfo extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AccountInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCustomerName = new javax.swing.JLabel();
        jlCustomerID = new javax.swing.JLabel();
        jlSavingsAcctID = new javax.swing.JLabel();
        jlSavingsAcctBalance = new javax.swing.JLabel();
        jlSSN = new javax.swing.JLabel();
        jlAddress = new javax.swing.JLabel();
        jlCity = new javax.swing.JLabel();
        jlZip = new javax.swing.JLabel();
        jlState = new javax.swing.JLabel();
        jlPhone = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlCheckingAcctBalance = new javax.swing.JLabel();
        jlCheckingAcctID = new javax.swing.JLabel();
        jtxtCustomerName = new javax.swing.JTextField();
        jtxtSSN = new javax.swing.JTextField();
        jtxtCustomerID = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtCity = new javax.swing.JTextField();
        jtxtState = new javax.swing.JTextField();
        jtxtZip = new javax.swing.JTextField();
        jtxtPhone = new javax.swing.JTextField();
        jtxtSavingsAcctID = new javax.swing.JTextField();
        jtxtSavingsAcctBalance = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtCheckingAcctID = new javax.swing.JTextField();
        jtxtCheckingAcctBalance = new javax.swing.JTextField();
        jbSave = new javax.swing.JButton();
        jbClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlCustomerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlCustomerName.setText("Customer Name:");

        jlCustomerID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlCustomerID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlCustomerID.setText("Customer ID:");

        jlSavingsAcctID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlSavingsAcctID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlSavingsAcctID.setText("Savings Account ID:");

        jlSavingsAcctBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlSavingsAcctBalance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlSavingsAcctBalance.setText("Savings Account Balance:");

        jlSSN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlSSN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlSSN.setText("SSN:");

        jlAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlAddress.setText("Address:");

        jlCity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlCity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlCity.setText("City:");

        jlZip.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlZip.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlZip.setText("ZIP:");

        jlState.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlState.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlState.setText("State:");

        jlPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlPhone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlPhone.setText("Phone:");

        jlEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlEmail.setText("Email:");

        jlCheckingAcctBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlCheckingAcctBalance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlCheckingAcctBalance.setText("Checking Account Balance:");

        jlCheckingAcctID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlCheckingAcctID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlCheckingAcctID.setText("Checking Account ID:");

        jtxtCustomerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtSSN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtCustomerID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtCity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtState.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtZip.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtSavingsAcctID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtSavingsAcctBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtCheckingAcctID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtCheckingAcctBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jbSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbSave.setText("Save Changes");

        jbClose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbClose.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlSavingsAcctID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlSavingsAcctBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlCheckingAcctBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlCheckingAcctID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlCustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlSSN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(jlAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(jlCity, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(jlZip, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(jlState, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(jlPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(jlEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtSSN, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtCustomerName)
                    .addComponent(jtxtCustomerID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtZip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtSavingsAcctID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtSavingsAcctBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtCheckingAcctID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtCheckingAcctBalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jbSave, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbClose, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlState, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtState, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlZip, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSavingsAcctID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSavingsAcctID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSavingsAcctBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSavingsAcctBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCheckingAcctID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCheckingAcctID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCheckingAcctBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCheckingAcctBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSave)
                    .addComponent(jbClose))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbSave;
    private javax.swing.JLabel jlAddress;
    private javax.swing.JLabel jlCheckingAcctBalance;
    private javax.swing.JLabel jlCheckingAcctID;
    private javax.swing.JLabel jlCity;
    private javax.swing.JLabel jlCustomerID;
    private javax.swing.JLabel jlCustomerName;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlPhone;
    private javax.swing.JLabel jlSSN;
    private javax.swing.JLabel jlSavingsAcctBalance;
    private javax.swing.JLabel jlSavingsAcctID;
    private javax.swing.JLabel jlState;
    private javax.swing.JLabel jlZip;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtCheckingAcctBalance;
    private javax.swing.JTextField jtxtCheckingAcctID;
    private javax.swing.JTextField jtxtCity;
    private javax.swing.JTextField jtxtCustomerID;
    private javax.swing.JTextField jtxtCustomerName;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtPhone;
    private javax.swing.JTextField jtxtSSN;
    private javax.swing.JTextField jtxtSavingsAcctBalance;
    private javax.swing.JTextField jtxtSavingsAcctID;
    private javax.swing.JTextField jtxtState;
    private javax.swing.JTextField jtxtZip;
    // End of variables declaration//GEN-END:variables
}
