
import java.awt.event.WindowEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author krm5188
 */
public class AccountInfo extends javax.swing.JFrame {

    Transaction bankTrans;
    Customer custCurrent;
    Teller currentUser;
    Account acctCurrent;
    
    public AccountInfo(Transaction trans, Customer cust) {

        bankTrans = trans;
        custCurrent = cust;
        jtxtCustomerID.setText(""+custCurrent.getCustomerIDnumber());
        jtxtLastName.setText(custCurrent.getLname());
        jtxtFirstName.setText(custCurrent.getFname());
        jtxtSSN.setText(custCurrent.getSocialSecurity());
        jtxtAddress.setText(custCurrent.getAddress());
        jtxtCity.setText(custCurrent.getCity());
        jtxtState.setText(custCurrent.getState());
        jtxtZip.setText(custCurrent.getZipcode());
        jtxtPhone.setText(""+custCurrent.getPhone());
        jtxtEmail.setText(custCurrent.getEmail());
    }
    
    private AccountInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlFirstName = new javax.swing.JLabel();
        jlCustomerID = new javax.swing.JLabel();
        jlSSN = new javax.swing.JLabel();
        jlAddress = new javax.swing.JLabel();
        jlCity = new javax.swing.JLabel();
        jlZip = new javax.swing.JLabel();
        jlState = new javax.swing.JLabel();
        jlPhone = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jtxtLastName = new javax.swing.JTextField();
        jtxtSSN = new javax.swing.JTextField();
        jtxtCustomerID = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtCity = new javax.swing.JTextField();
        jtxtState = new javax.swing.JTextField();
        jtxtZip = new javax.swing.JTextField();
        jtxtPhone = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jbSave = new javax.swing.JButton();
        jbClose = new javax.swing.JButton();
        jlLastName = new javax.swing.JLabel();
        jtxtFirstName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlFirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlFirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlFirstName.setText("Customer First Name:");

        jlCustomerID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlCustomerID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlCustomerID.setText("Customer ID:");

        jlSSN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlSSN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlSSN.setText("SSN:");

        jlAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlAddress.setText("Address:");

        jlCity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlCity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlCity.setText("City:");

        jlZip.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlZip.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlZip.setText("ZIP:");

        jlState.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlState.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlState.setText("State:");

        jlPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlPhone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlPhone.setText("Phone:");

        jlEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlEmail.setText("Email:");

        jtxtLastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtSSN.setEditable(false);
        jtxtSSN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtCustomerID.setEditable(false);
        jtxtCustomerID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtCity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtState.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtZip.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jbSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbSave.setText("Save Changes");
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        jbClose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbClose.setText("Close");
        jbClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCloseActionPerformed(evt);
            }
        });

        jlLastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlLastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlLastName.setText("Customer Last Name:");

        jtxtFirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlCustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlSSN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jlAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jlCity, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jlZip, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jlState, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jlPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jlEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jlLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtSSN, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtLastName)
                    .addComponent(jtxtCustomerID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtZip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtxtFirstName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jbSave, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jbClose, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlState, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtState, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlZip, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSave)
                    .addComponent(jbClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCloseActionPerformed
        this.dispose();
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        new MainScreen(currentUser,bankTrans,custCurrent,acctCurrent).setVisible(true);
    }//GEN-LAST:event_jbCloseActionPerformed

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        custCurrent.setFname(jtxtFirstName.getText());
        custCurrent.setLname(jtxtLastName.getText());
        custCurrent.setAddress(jtxtAddress.getText());
        custCurrent.setCity(jtxtCity.getText());
        custCurrent.setState(jtxtState.getText());
        custCurrent.setPhone(Integer.parseInt(jtxtPhone.getText()));
        custCurrent.setZipcode(jtxtZip.getText());
        bankTrans.updateCustomer(custCurrent);
    }//GEN-LAST:event_jbSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbSave;
    private javax.swing.JLabel jlAddress;
    private javax.swing.JLabel jlCity;
    private javax.swing.JLabel jlCustomerID;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlFirstName;
    private javax.swing.JLabel jlLastName;
    private javax.swing.JLabel jlPhone;
    private javax.swing.JLabel jlSSN;
    private javax.swing.JLabel jlState;
    private javax.swing.JLabel jlZip;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtCity;
    private javax.swing.JTextField jtxtCustomerID;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtLastName;
    private javax.swing.JTextField jtxtPhone;
    private javax.swing.JTextField jtxtSSN;
    private javax.swing.JTextField jtxtState;
    private javax.swing.JTextField jtxtZip;
    // End of variables declaration//GEN-END:variables
}
